version: '3.4'

services:
  entertainmentapp:
    image: entertainmentapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
