import type { Metadata } from 'next';
import './globals.css';
import { outfit } from '../fonts/fonts';
import { Navbar } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={outfit.className}>
      <body className="min-h-screen grid grid-rows-[56px_1fr]">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
