import type { Metadata } from "next";
import "./globals.css";
import { outfit } from "../fonts/fonts";
import { Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={outfit.className}>
      <body className="grid min-h-screen grid-rows-[auto_1fr] bg-main-blue-very-dark 2xl:grid-cols-[auto_1fr] 2xl:grid-rows-1">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
